name: Publicar Documentación

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install DocFX
        run: dotnet tool install -g docfx --version 2.60.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install JSDoc
        run: npm install -g jsdoc
      
      - name: Generate Backend Documentation
        run: |
          mkdir -p docs/api/backend
          docfx init -q -o docs/api/backend
          docfx docs/api/backend/docfx.json || echo "DocFX completed with warnings"
      
      - name: Generate Frontend Documentation
        run: |
          mkdir -p docs/api/frontend
          if [ -d "frontend/src" ]; then
            jsdoc frontend/src -r -d docs/api/frontend
          else
            echo "Frontend documentation placeholder" > docs/api/frontend/index.html
          fi
      
      - name: Build Documentation Site
        run: |
          mkdir -p docs/site
          cp -r docs/api docs/site/ || true
          cp -r docs/diagrams docs/site/ 2>/dev/null || mkdir -p docs/site/diagrams
          
          # Crear página principal de documentación
          cat > docs/site/index.md << 'EOF'
          # 📚 Documentación Babysitter App
          
          Bienvenido a la documentación completa del sistema de gestión de niñeras.
          
          ## 🏗️ Arquitectura del Sistema
          
          - **Backend**: .NET Core 8.0 + Entity Framework + MySQL
          - **Frontend**: React 18 + TypeScript + Material-UI  
          - **Infraestructura**: Google Cloud Platform + Terraform
          - **CI/CD**: GitHub Actions
          
          ## 📊 Diagramas Disponibles
          
          ### Infraestructura
          - [Diagrama de Infraestructura](diagrams/terraform-graph.png)
          - [Documentación de Terraform](infra-docs.md)
          
          ### Código
          - [Diagrama de Clases Backend](diagrams/backend-class-diagram.png)
          - [Diagrama de Componentes Frontend](diagrams/frontend-component-diagram.png)
          
          ## 📖 Documentación API
          
          ### Backend (.NET Core)
          - [Documentación API Backend](api/backend/)
          - **Endpoints principales**:
            - `/api/auth` - Autenticación
            - `/api/users` - Gestión de usuarios
            - `/api/nannies` - Gestión de niñeras
            - `/api/bookings` - Sistema de reservas
            - `/api/reviews` - Sistema de reseñas
          
          ### Frontend (React)
          - [Documentación Frontend](api/frontend/)
          - **Componentes principales**:
            - Autenticación y registro
            - Búsqueda de niñeras
            - Sistema de reservas
            - Perfil de usuario
          
          ## 🚀 Inicio Rápido
          
          ### Desarrollo Local
          
          #### Backend
          ```bash
          cd backend/BabysitterApi
          dotnet restore
          dotnet run
          ```
          
          #### Frontend
          ```bash
          cd frontend
          npm install
          npm start
          ```
          
          #### Base de Datos
          ```bash
          docker-compose up mysql
          ```
          
          ### Despliegue en Producción
          
          El sistema se despliega automáticamente en Google Cloud Platform cuando se hace push a la rama `main`.
          
          ## 📞 Enlaces Útiles
          
          - [Repositorio GitHub](https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02)
          - [Issues y Bugs](https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02/issues)
          - [Wiki del Proyecto](https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02/wiki)
          
          ---
          
          **Última actualización**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          **Generado automáticamente** por GitHub Actions
          EOF
          
          # Crear archivo HTML simple para navegación
          cat > docs/site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Babysitter App - Documentación</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
                  .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 4rem 0; }
                  .card { transition: transform 0.2s; }
                  .card:hover { transform: translateY(-5px); }
              </style>
          </head>
          <body>
              <div class="hero">
                  <div class="container text-center">
                      <h1 class="display-4">📚 Babysitter App</h1>
                      <p class="lead">Documentación Completa del Sistema</p>
                  </div>
              </div>
              
              <div class="container my-5">
                  <div class="row">
                      <div class="col-md-4 mb-4">
                          <div class="card h-100">
                              <div class="card-body">
                                  <h5 class="card-title">🏗️ Infraestructura</h5>
                                  <p class="card-text">Diagramas y documentación de la infraestructura en Google Cloud.</p>
                                  <a href="diagrams/terraform-graph.png" class="btn btn-primary">Ver Diagrama</a>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-4 mb-4">
                          <div class="card h-100">
                              <div class="card-body">
                                  <h5 class="card-title">🔌 API Backend</h5>
                                  <p class="card-text">Documentación de la API .NET Core y endpoints disponibles.</p>
                                  <a href="api/backend/" class="btn btn-primary">Ver Docs</a>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-4 mb-4">
                          <div class="card h-100">
                              <div class="card-body">
                                  <h5 class="card-title">⚛️ Frontend</h5>
                                  <p class="card-text">Documentación de componentes React y estructura del frontend.</p>
                                  <a href="api/frontend/" class="btn btn-primary">Ver Docs</a>
                              </div>
                          </div>
                      </div>
                  </div>
                  
                  <div class="row mt-5">
                      <div class="col-md-6">
                          <h3>📊 Diagramas Disponibles</h3>
                          <ul class="list-group">
                              <li class="list-group-item"><a href="diagrams/terraform-graph.png">Infraestructura GCP</a></li>
                              <li class="list-group-item"><a href="diagrams/backend-class-diagram.png">Clases Backend</a></li>
                              <li class="list-group-item"><a href="diagrams/frontend-component-diagram.png">Componentes Frontend</a></li>
                          </ul>
                      </div>
                      <div class="col-md-6">
                          <h3>🚀 Enlaces Rápidos</h3>
                          <ul class="list-group">
                              <li class="list-group-item"><a href="https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02" target="_blank">Repositorio GitHub</a></li>
                              <li class="list-group-item"><a href="https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02/issues" target="_blank">Issues</a></li>
                              <li class="list-group-item"><a href="https://github.com/UPT-FAING-EPIS/examen-2025-ii-pds-u1-Brunoenr02/wiki" target="_blank">Wiki</a></li>
                          </ul>
                      </div>
                  </div>
              </div>
              
              <footer class="bg-light text-center py-3 mt-5">
                  <p class="mb-0">Generado automáticamente por GitHub Actions • Babysitter App © 2025</p>
              </footer>
          </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/site
          branch: gh-pages